version: "3.8"
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: michelle
      POSTGRES_PASSWORD: michelle123
      POSTGRES_DB: express-management
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: "postgresql://michelle:michelle123@database:5432/express-management"
    ports:
      - "3001:3000"
    depends_on:
      - database

volumes:
  postgres_data:
